### ISSUE TITLE
vektor-inc.co.jpで一部のブロックをコピーできる仕組みを作ったほうが良いのではないでしょうか

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-simple-copy-block#1]
(先日の合宿の際に少し @doshimaf  さんとお話していたのですが、)vektor-inc.co.jpで一部のブロックをコピーできる仕組みを作ったほうが良いのではないでしょうか

※ issuesはvk-blocksにしましたが、このリポジトリーで実装するわけではないと思います

既にissuesやパターンとしてありますが、見出し、ボタン、画像などでさまざまなバリエーションをもつパターンを作りたい場面があると思います
https://github.com/vektor-inc/vk-blocks-pro/issues/563
https://patterns.vektor-inc.co.jp/vk-patterns/button-through-arrow/
https://github.com/vektor-inc/vk-block-patterns/issues/28

それを一つ一つパターンディレクトリーに登録すると小さなパターンすぎて一覧性が低くなっていくと思います
ただ１ページに例えば見出しのパターンをパターンディレクトリーに登録すると全ての見出しを利用するケースは無いと思うので使いずらい

私のアイディアとしてはvektor-inc.co.jp内のブログ内でコピペできる仕組みを作ったほうがカスタマイズの説明文なども自由に入れられるので良いのではないかと思っています
そのための仕組みを作ったほうが良いのではと思うのですがどうでしょうか？

**Comment by shimotmk** [comment]
ブログなどで一部のブロックのパターンを紹介するケースがあるので.orgで配布することも想定している。
(石川さんの想定より)

**Comment by shimotmk** [comment]
すみません。(一応全員にメンションしておきます。)
@ChiakiKouno @doshimaf @drill-lancer @goutetsuguma @kaorock72 @kurudrive @mthaichi @sysbird
当初の想定より汎用性を出すことを考えて、以前のものからブロックの構成、設定を修正しました。

お手数ですが、リリース前に必要な機能や感想などあればいただきたいです。

zip
[vk-simple-copy-block.zip](https://github.com/vektor-inc/vk-simple-copy-block/files/11046822/vk-simple-copy-block.zip)

pull
#2

**Comment by ChiakiKouno** [comment]
@shimotmk 

ひとまずの感想、シンプルで使いやすいですー！ありがとうございます！（zipも助かりました！）
ボタンの機能で左右中央寄せがあるのもいいですね！一瞬ボタンのテキストにも左右と中央寄せ機能があるのいつ使うかな？と思ったんですが、ボタンの横幅を50%とか100％で使ったりするときにテキストのボタンを右に寄せられて「おおー」っとなりました◎
触りながら迷わず使えたのでとても良いなと思いました。

他、確認点をまとめてみますね。(6.2-RC3)で試しました！

- ボタンを右よせ（Justify items right）にしたところ、編集画面では中央寄せになっていました。フロントではちゃんと右寄せでした。コアのバグだったらすみません！
- wp-block-vk-simple-copy-block-copy-button-wrap のブロックを選択して、マージンを選べるようになっていると思います。編集画面では「Margin」となっていて、指定してみると「Margin-top」の指定になるようでしたので、編集画面で「Margin Top」とするか、「Margin」のままで、上下左右の指定ができると良いのかなと思いました。私個人はマージン左右は使わなそうですが、上に加えて下も指定できると便利そうと思いました。

取り急ぎ以上です〜

**Comment by shimotmk** [comment]
@ChiakiKouno 
ありがとうございます！

>  ボタンを右よせ（Justify items right）にしたところ、編集画面では中央寄せになっていました。フロントではちゃんと右寄せでした。コアのバグだったらすみません！

修正しておきました🙇‍♂️

> wp-block-vk-simple-copy-block-copy-button-wrap のブロックを選択して、マージンを選べるようになっていると思います。編集画面では「Margin」となっていて、指定してみると「Margin-top」の指定になるようでしたので、編集画面で「Margin Top」とするか、「Margin」のままで、上下左右の指定ができると良いのかなと思いました。私個人はマージン左右は使わなそうですが、上に加えて下も指定できると便利そうと思いました。

Margin Bottomを使う人がいるかわからなかったですが、確かに少しわかりにくさもあったのでBottomを追加しました！

**Comment by goutetsuguma** [comment]
@shimotmk 

いろいろ設定が増えていてすごく使いやすいです！ありがとうございます！！

テーマ：X-T9　WP 6.2-RC3の環境で使ってみました。

X-T9ですと、背景色を入れると以下のpadding: 0;が上書きされて、paddingがなくなってしまうようでした。（パディング入れ直せばOKです）

```
.has-background, :is(.wp-block-group):where(.has-background) {
    padding: 0;
}
```

クラス名を追加して、ボタンのpaddingの指定を強くするのはどうでしょうか。
ご検討よろしくお願いいたします。

**Comment by doshimaf** [comment]
@shimotmk 
ブロックの構成や余白設定などわかりやすく、とても使いやすく感じました
ありがとうございます！

ページ内でボタンデザインが異なることもないと思うので、カスタムCSSの設定欄がないところやその他ボタン単体への設定項目が少ないところも名前の通りシンプルでとても使いやすいと思います。

その他使用感で気になるところは今の所ありませんでした。

**Comment by sysbird** [comment]
@shimotmk 
いろいろ設定できて使いやすいと思いました
ボタンの幅の%を指定する方法もいいですね

私が使うとしたら、
ターゲットに枠をつけたいので、このときコピーボタンが枠にくっついているとターゲット感がでる気がします
あくまでも個人的な感覚ですので、スルーでもOK
![copy](https://user-images.githubusercontent.com/4631838/227420373-7c776945-ec81-4787-925b-ae0655ab5aeb.jpg)

**Comment by sysbird** [comment]
> ターゲットに枠をつけたいので、このときコピーボタンが枠にくっついているとターゲット感がでる気がします
失礼しました
ここマージン設定できますね、さすがです

**Comment by kurudrive** [comment]
@goutetsuguma @shimotmk 

> クラス名を追加して、ボタンのpaddingの指定を強くするのはどうでしょうか。
ご検討よろしくお願いいたします。

これは現状ままでOKです
