### ISSUE TITLE
すべてのブロックのデザインを一括制御する機能が欲しい（初期実装じゃなく追加実装でOK）

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#10]
プラグインの性質上ブロック１つ１つというよりはサイト全体で同じデザインにする方が多いと思われるため、
設定画面などから一括制御したい

例）

インナーブロックの
* 線
* 余白

ボタンの
* 文言
* 色
* 文字サイズ

ただ、一旦配置済みのブロックに対しても割り当てるにはDOMは同じで極力CSSだけで制御する必要がありそう。

**Comment by shimotmk** [comment]
この機能を使う想定できないのですが、どういうことを考えていますか？

スタイル(CSS)に関しては全体で後から変えたい人はカスタマイザーのCSSなり独自で管理しているCSSファイルなど管理しやすい形で調整すると思います。

ボタンの文言に関してはサイト全体で後から変えたいケースがわからないです。
多分このブロックを使う人は「見出しのパターンをコピーする」や「このボタンをコピーする」などのコピー対象のブロックや内容によって文言が変わるので記事を作った時以外にサイト全体で変えたいケースが想像できないです。

普通のブロックのようにブロックごとにスタイルや文言を変更したいケースはあるかなと思いますが、全体を一括でということは想像ができません。

**Comment by kurudrive** [comment]
@shimotmk 確認ありがとうございます。

まず、

CSSが得意でない人も標準ブロックの組み合わせだけで使う事も想定される
（メインの用途ではないのでこれはそんなに重要じゃない）

のと、
GUIからデザイン設定できなければもちろん追加CSSなどから書く事になりますが

* CSSを書くためにDOM構造とクラス名が何か調べる必要がある（「そんなんすぐやろ」と思うかもしれないが、例えばLightningのヘッダーやフッターの非表示なんて、そのページの CSSに header { display:none; } 書けばいいだけなのにそれを面倒と感じたり、それを気づかずに非表示のやり方を知りたいという質問が定期的に来ていた）実際チェックボックスで非表示指定を実装したら非常に喜ばれた
（とは言え単純な非表示と今回のケースでは実装負荷が全然違うが...）
* 独自のCSSファイルは読み込む設定をするのが手間
* カスタマイザーの追加CSSは とりあえずクラス名調べるのが面倒 / あそこ書くと後からどこで指定したかりにくい（あそこに沢山書いてあると特に）/ テーマ変えると反映されない

→ CSSが書ける人でも、カスタム書式設定みたいに管理画面からポチポチできる方が圧倒的に楽
（「まぁプロ向けだからCSSは手書きか...まぁそうよね」か「めっちゃ便利やん！」かという印象の違いが発生する）

という想定です。
ただ、「CSS書けば出来る」という面はたしかにあるので後日検討でもよいという認識です。

ボタンの名前は、下村さんの指摘の通り

> 「見出しのパターンをコピーする」や「このボタンをコピーする」などのコピー対象のブロックや内容によって文言が変わる

はあると思います。それとは別に単純にサイト全体として

> 「コピー」じゃなくて、「このパターンをコピー」にしたい。
> でもブロック一個ずつ毎回「このパターンをコピー」で指定するのは面倒くさい

というケースを想定しています。まぁでもこれに関してはデザインに比べれば部分的に「ボタンをコピー」や「見出しをコピー」にしたりするケースがあるので、重要度は低い認識です。

**Comment by shimotmk** [comment]
@kurudrive 
> CSSが得意でない人も標準ブロックの組み合わせだけで使う事も想定される

このような人を想定するのであれば尚更ブロック個別で修正するだけの方がわかりやすいと思います。

ヘッダーなどはブロックではないのでわかりますが、このプラグインはブロックなのでブロックをサイト全体で後から変えたいケースがわからないです。
ブロックはコンテンツなので投稿画面を開いて編集しない限り変更されて欲しくないのが通常の考え方かと思います。

**Comment by kurudrive** [comment]
@shimotmk 

> サイト全体で後から変えたいケースがわからないです。

えーっと、後からというよりまず最初ですかね。
このブロックのデザインをどうするのか、枠線や余白をどうするかは好みがわかれるので、その設定を最初に管理画面で行えると楽だなという考えです。

一昔で言えば例えば目次を表示するプラグインって、目次をどういうデザインにするかは管理画面で何パターンか用意してあって、それからラジオボタンで選ぶとかになってたのですが、そういう感じで、
（あらかじめ決め打ちでデザインを数パターン用意してもよいのですが、みなさんブロックエディタの感覚に慣れちゃってるからユーザーが色や余白は個別で指定できる感じの方が喜ばれるかなと）
目次のデザインがページによって違ったりせずにサイト全体で同じになってますよね？
同じように、コピーするためのブロックが場所によってデザインがバラついたりしないで、統一されている方が良いと個人的には思うので、毎回個別に指定するのではなくて一括管理したいなというのはそういうケースです。

でも今回はブロックの性質上、見出し用のパターンとボタン用のパターンで色を変更したいという要望は当然あると思うので、
ブロック個別でのデザイン指定機能も需要は高いと僕は思います。

それと、例えばブロック個別で色を指定してしまっていると、後からテーマ変更した時に、
線の色やインナーの余白が合わないので変更したいとなった時に、
配置したブロック全部手動で修正になってしまうので、
ブロック個別に色や余白をつけるのではなく一括管理できた方がありがたいと思います。

> 投稿画面を開いて編集しない限り変更されて欲しくないのが通常の考え方

これは僕は逆の考え方で、例えば投稿画面毎で変更されて欲しくないと思ったりします。

このあたりは、たくさん利用者がいてそれぞれ好みのわかれるところで、どれが正解とかではないと思うので、
リリースして様子を見ながら追加検討で良いと思ってます🙂

**Comment by kurudrive** [comment]
まぁそんなに沢山配置しまくるようなブロックでは無いので、デザイン個別指定でも概ね対応はできると思うのですが、
例えばインナーブロックの枠線に色指定したとして、その色のカラーパレットがテーマ変更したら新しいテーマにはその色が存在しないから全部色が抜けちゃうとか...
まぁそれなら古い色のクラス名に対して手書きCSSで色を当てれば良いのですが、テーマ変更後に配置したブロックの方はじゃあ新しいパレットで色を割り当てるのかというとあー、どうしよっかなみたいになるので、そういうのを想定して一括管理したいなと僕は思ってる感じでございます！伝わるかな（・ｗ・？

**Comment by shimotmk** [comment]
@kurudrive 
> 例えばインナーブロックの枠線に色指定したとして、その色のカラーパレットがテーマ変更したら新しいテーマにはその色が存在しないから全部色が抜けちゃうとか...

それはこのプラグインに関わらずどのブロックでも同じなのでテーマを変えることをした人が考える範囲だと思います。
このプラグインがカバーする範囲では無いと思っています。

**Comment by kurudrive** [comment]
うーん、いや...えー...

* このプラグインのブロックのデザインに関する事項
* このプラグインの管理画面からこのブロックのデザイン指定する方式ならテーマや背景色など変更してもそのまま問題なく対応できる
  → テーマを変える事をした人は特に考える事なく移行できる

という事を踏まえると、このプラグインがカバーする範囲と考える事はおかしくないと思うけどなぁ...

もちろん実装コストのかかる話なので手放しですぐに進めようとも思わないけど...

**Comment by shimotmk** [comment]
このプラグインはテーマ移行をサポートするプラグインではないと思うのでテーマに依存するカラーを選択されていたらカラーなどが変わるのは自然だと思います。

他のブロックと異なる動きをされた方が逆に余計な機能であると感じると思います
