### ISSUE TITLE
別ブランチでアップデートチェッカーを入れようと思いますがどうでしょう？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#14]
公式のプラグインディレクトリはレビュー待ちがどんどん増えてて、現在

* コアのレビュアーが辞めた
* テーマと違ってプラグインはレビュアーもクローズドな指名なのでボランティアが助ける事はできない
* AIによるプラグイン量産・申請が加速してる

という状況を踏まえるとおそらく解消にかなり時間がかかるのではないかと思います。

と、いう事で、別ブランチでアップデートチェッカー入れてしまって当面それで運用しようかと思いますがどうでしょう？

**Comment by shimotmk** [comment]
コアのレビューが滞っているのはどうしようも出来ないのですが、野良プラグインで出した後に公式で出すと注目が分散しませんかね。。

**Comment by kurudrive** [comment]
@shimotmk 本当は同時に出したいけどレビュー全く進んでないっぽくて（ 今日の時点で 400に増えてる... https://wordpress.org/plugins/developers/add/ ）全く目処が立たないのでもうアップデートチェッカー入れて貰って一旦だそうかと思うんだけどどう？待つ？

**Comment by kurudrive** [comment]
公式ディレクトリ公開につきclose
