### ISSUE TITLE
GitHubからのデプロイを設定する

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#19]
とりあえず svn で直接アップしました。
GitHubからのデプロイの設定よろしくお願いいたします。
https://wordpress.org/plugins/vk-simple-copy-block/

**Comment by shimotmk** [comment]
いくつかタグを打って試してみます

**Comment by shimotmk** [comment]
こちらの設定は完了しました

**Comment by kurudrive** [comment]
@shimotmk ありがとうございます。
