### ISSUE TITLE
Translation not applied?

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#27]
I already approved the translation but not applied on edit screen.
How about your environment? Please Check this  (￣人￣)

https://translate.wordpress.org/projects/wp-plugins/vk-simple-copy-block/stable/ja/default/

**Comment by shimotmk** [comment]
Maybe the code issue has been resolved.

The description of the block will be adapted if you translate it again.
https://translate.wordpress.org/projects/wp-plugins/vk-simple-copy-block/dev/ja/default/

**Comment by kurudrive** [comment]
@shimotmk I have a question.
Which you prefer the "Copy Target" translate to "コピーターゲット" or "コピー対象"?

**Comment by shimotmk** [comment]
@kurudrive 
I prefer "コピーターゲット".
The article was like that.
https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-simple-copy-block/

**Comment by kurudrive** [comment]
@shimotmk OK. I did it :)
If you have any change request, please feel free to send suggestion.
https://translate.wordpress.org/projects/wp-plugins/vk-simple-copy-block/dev/ja/default/

Thank you.
