### ISSUE TITLE
ボタンの表記を変更出来る機能があると...あれ...いらない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#3]
初期リリースじゃなくて良いのですが、

たぶん人によって

* このパターンをコピー
* この見出しをコピー

みたいにしたいかなーと思ったけど、
沢山配置するといちいち変更するの面倒で結局使われないかな？

**Comment by shimotmk** [comment]
これ初期リリースで行わないと相当厳しいと思うので入力欄を作ろうと思います
