### ISSUE TITLE
公式ディレクトリに登録するまでに必要なタスクをリストアップする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#4]
必要な作業 / 公式ディレクトリに入れるにあたって初期段階で入れておきたい機能など

- [x] 名称決定
- [x] 必要最小限のデザイン調整
- [x] カバー画像作成
- [x] アイコン画像作成

~~簡単な使い方動画~~ 一旦キャプチャ画像のみでOKとする

**Comment by ChiakiKouno** [comment]
@kurudrive 簡単な使い方動画の作成がきっとまだですよね、佐々木さんにお願いしますか？

**Comment by kurudrive** [comment]
@ChiakiKouno Concerning about Japanese, I feel it's ok only this video don't you think so?
https://www.youtube.com/watch?v=WsHckw_bIQI&t=109s

**Comment by ChiakiKouno** [comment]
2023/6/29 [マーケMTG](https://www.notion.so/MTG-2023-6-29-2023-6-29-416f6140971d4d0699d2d75e7c71163e?pvs=4#4ffe55b116f34178b31bb94735bac489)にて

- [ ] Twitter画像の英語版を作成しよう（定期Tweet）
- [ ] orgのプラグインページはそれなりに内容を入れる（説明＋キャプチャ画像）
