### ISSUE TITLE
ブロックの正式名どうする？ → VK Simple Copy Block に変更

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#5]
公式ディレクトリに申請する事になったので一応改めて確認。

現状

vk-copy-inner-block/copy-inner

長いので

vkcib/coppy-inner 

とか

vk-cib/coppy-inner 

にする？

**Comment by kurudrive** [comment]
主に
@shimotmk @drill-lancer @mthaichi @sysbird @doshimaf 
個人的にはそのまま vk-copy-inner-block/copy-inner でええんちゃう？ と思ってますがどう？

**Comment by kurudrive** [comment]
あぁ... vk-cib/coppy-inner ならそれはそれでアリか...

**Comment by kurudrive** [comment]
もし変更するなら変更しないといけない所が発生したりCSSあてたりするのに影響したりするので優先度上げました

**Comment by kurudrive** [comment]
VK Simple Copy Block になりました！

**Comment by shimotmk** [comment]
あっブロックnameはvk-simple-copy-block/simple-copyでtitleはシンプルコピーですかね。。。

**Comment by drill-lancer** [comment]
名前決まったので Close
