### ISSUE TITLE
プラグインディレクトリ用のカバー画像作成

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#7]
名称自体は ↓ が決まってからだと思うけど、名称以外でできそうな所は先行して作業いただいても可 
https://github.com/vektor-inc/vk-copy-inner-block/issues/5

**Comment by goutetsuguma** [comment]
@kurudrive 
@ChiakiKouno 

カバー画像作成しましたので、ご確認お願いいたします

キャッチは[Chiakiさんのキャッチ](https://github.com/vektor-inc/vk-simple-copy-block/issues/9)の考えていただいたキャッチをいれました。とてもわかりやすくて良いと思います！
下のリード文章、とりあえず英語入れてみたのですが、いい感じの文章があれば差し替えます。ご確認お願いいたしますmm
![banner-1544x500](https://user-images.githubusercontent.com/5525368/227088591-9053e545-bcf6-427c-8659-dc81262d5ab5.png)



▼Figma データ
https://www.figma.com/file/g3xlLgRrh2WMr9TPeBeq02/VK-Simple-Copy-Block?node-id=0%3A1&t=Zz6u2oSjHuFCC2fP-1

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございます！良いと思いますー！

**Comment by ChiakiKouno** [comment]
@goutetsuguma 同じく良いと思いましたー＾＾ ありがとうございます！

**Comment by kurudrive** [comment]
@goutetsuguma 

このリポジトリにコミットしておいてー！

**Comment by goutetsuguma** [comment]
@kurudrive 

バナー入れまして、プルリクだしました！ご確認お願いいたします！
https://github.com/vektor-inc/vk-simple-copy-block/pull/24

**Comment by ChiakiKouno** [comment]
公式ディレクトリに公開になったので、きっとこちら完了と思われます。
くのうさん、ありがとうございましたー！！
