### ISSUE TITLE
キャッチコピーを考える

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-simple-copy-block#9]

**Comment by ChiakiKouno** [comment]
プラグイン名称とセットで書いてみておきます。

VK Simple Copy Block
Add Copy Button for Your Block Patterns

VK Simple Copy Block
Custom Block Pattern Library plugin

VK Simple Copy Block
Create Your Original Block Pattern Library

他にもぜひあれば…！

**Comment by ChiakiKouno** [comment]
今日の時点の概要文、日本語と英語を置いておきます。ドラフトでまだ誰からもOKもらってないものです。
https://hackmd.io/amgD-bQ8RQu-QBwCFkINOA#%E6%A6%82%E8%A6%81%E6%96%87

**Comment by ChiakiKouno** [comment]
@kurudrive ご確認ありがとうございますー！＾＾

すみません、きっと私の日本語が曖昧でしたねmm

▼元の文章下記でした：

> よく使うブロックパターンを1つの記事にリスト化して管理する場合に便利です。
> 
> また、あなたがデザイナーの場合、あなたが作成した魅力的なブロックパターンをいろんな方が簡単に使用できるよう公開する事もできるようになります。

同じ機能のことを、違う角度からこんな使い方もどうぞ、言いたかったです。
上記だときっと追加の機能があるように見えましたね。
下記だといかがでしょうか？

▼書き換え案：

> よく使うブロックパターンを1つの記事にリスト化して管理する場合に便利です。または、あなたがデザイナーの場合、あなたが作成した魅力的なブロックパターンをいろんな方が簡単に使用できるよう一般公開するといった使い方もできます。

**Comment by ChiakiKouno** [comment]
あ、そもそも後半の使い方するのは、この公式ディレクトリ用ではスコープ外だったかしら…

**Comment by kurudrive** [comment]
@ChiakiKouno 

最初の

> あなたのオリジナルデザインのブロックパターンを公開し、WordPress Block Pattern Libraryのようなページやサイトを作成したいですか？

が、「WordPress Block Pattern Libraryのようなページやサイトを作成」はこのプラグインの趣旨とは違う（それは https://github.com/vektor-inc/vk-pattern-directory-creator が担当 ）ので、ここを削って、最後に書いてあった

> よく使うブロックパターンを1つの記事にリスト化して管理する場合に便利です。
> また、あなたがデザイナーの場合、あなたが作成した魅力的なブロックパターンをブログの記事などにいろいろ貼り付けて、
> ユーザーが簡単に使用できるよう公開する事もできるようになります。

を最初に持ってくる感じでどうかなと（・ｗ・

**Comment by ChiakiKouno** [comment]
@kurudrive あ、なるほどそのように切り分けているのですね、理解が遅くてすみません！かしこまりです！

**Comment by ChiakiKouno** [comment]
@kurudrive and all,

概要文、今日のところの内容にアップしました！
https://hackmd.io/amgD-bQ8RQu-QBwCFkINOA#%E6%A6%82%E8%A6%81%E6%96%87
（日本語確定したらすぐ英文にしますね！）

今の私の認識ですと、キャッチコピー案は

「VK Simple Copy Block」
Add Copy Button for Your Block Patterns

がしっくりくるかなと思います。

追加のご意見などお待ちしております！

**Comment by ChiakiKouno** [comment]
キャッチコピー、
**Add Copy Button for Your Block Patterns**
にて、そのまま行けちゃったようなので、こちらのタスクはクローズしておきますね！

概要詳細どうするのか、掲載するのかなどはまた別のタスクにします。
